##
## Copyright (c) 2018-2024 M. Schuler, TTZ-EMO, Technical University of Applied Sciences Wuerzburg-Schweinfurt.
##
## This file is part of PyEMMO
## (see https://gitlab.ttz-emo.thws.de/ag-em/pyemmo).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.9.13
        # args: [--safe]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    # -   id: fix-encoding-pragma # fails with black formatting...
    -   id: trailing-whitespace
    -   id: debug-statements

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: '1.8.0'
#     hooks:
#     -   id: mypy
#         files: pyemmo
#         args: []
