# Make sure to **NOT** run tox from a virtualenv made from a pyenv python installation!
# pyenv-interpreter discovery does only work properly if the respective python versions
# are available through global or local pyenv config.
#
# Everything < Python 3.9 is outdated by now, so we don't try to keep is stable below
# this version!

[tox]
env_list =
    py{39,310,311,312,313,314,315}
minversion = 4
skip_missing_interpreters = false

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
    pytest_check
    hypothesis
    pytest-cov
    git+https://github.com/eomys/SciDataTool.git
    git+https://github.com/eomys/pyleecan.git@upgrade-python-version
commands =
    pytest {tty:--color=yes} {posargs}
