[tox]
envlist = py39
skipsdist = true

[testenv]
deps =  pytest
        -r requirements-test.txt
commands = 
            pip install pyleecan==1.5.1 --no-deps
            # pip install h5py
            pytest tests
        ;   Add pyemmo.pth file automatically
setenv =
        PATH = {env:PATH}{:}/.
