# Make sure to **NOT** run tox from a virtualenv made from a pyenv python installation!
# pyenv-interpreter discovery does only work properly if the respective python versions
# are available through global or local pyenv config.
#
# Everything < Python 3.9 is outdated by now, so we don't try to keep is stable below
# this version!
# py3.10: Not working with PYLEECAN yet. Fails to install matplotlib 3.3.4 with
#           build and setup.cfg due to freetype missing MS C++ compilers
# py3.11: Not working with PYLEECAN yet. Not compatible with pyleecan yet due
#           to PyQt5 (needed by pyleecan, but not available in Python 3.11).
#
# TODO: Create test environments to install and test with pyleecan

[tox]
env_list =
    py312, py311, py310, py39, py38
minversion = 4
skip_missing_interpreters = false

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
    pytest_check
    hypothesis
    pytest-cov
commands =
    pytest {tty:--color=yes} {posargs}
